### ISSUE TITLE
字体样式的侵入性问题

### ISSUE THREAD

**Issue by wingmeng** [zTree/zTree_v3#348]
样式文件 `zTreeStyle.css` 的第一行样式代码：
``` css
.ztree * {padding:0; margin:0; font-size:12px; font-family: Verdana, Arial, Helvetica, AppleGothic, sans-serif}
```
前面的 `padding:0; margin:0; ` 无可厚非，但后面对字体大小和字体系列的设置，放在此处就不太合适了，后代选择器的权重较高，这条样式的侵入性太强了。

例如：我想在节点名称里使用HTML内容，包含一些 iconfont 的引入。
```
var	setting = {
  view: {
    showIcon: false,
    nameIsHTML: true
  }
};
var zNodes = {
  id: 1,
  name: '<i class="glyphicon glyphicon-info-sign"></i> 测试文字'
};
```
那么，`.ztree *` 的字体声明显然会覆盖 `.glyphicon` 的字体声明，字体图标毫无疑问无法渲染出来。
![image](https://user-images.githubusercontent.com/9009389/42928014-c1f48dec-8b68-11e8-92cb-77a84eaee85c.png)

【建议】
对字体的定义使用 CSS 中的继承更合适。只需为 .ztree 这个祖先容器添加字体声明即可，后代元素会自动继承，同时不会影响其他自定义的字体。
``` css
.ztree * {padding:0; margin:0;}
.ztree {margin:0; padding:5px; font-size:12px; font-family: Verdana, Arial, Helvetica, AppleGothic, sans-serif; color:#333}
```
