### ISSUE TITLE
能否为叶节点 li 添加 class

### ISSUE THREAD

**Issue by jamesfancy** [zTree/zTree_v3#48]
我有一棵三层的树，第三层为叶节点，因为需要叶节点横向显示，所以我改了下样式：

``` css
.ztree {
    ul.level2 {
        padding-bottom: 2px;
        margin-bottom: 3px;
        border-bottom: 1px solid @grid-line;

        li {
            &.level3 {
                display: inline;
                width: 200px;

                .switch {
                    visibility: hidden;
                } 
            }
        }   
    }
}
```

现在，部分支只有2层，我就不知道该怎么办了。如果叶节点的li可以添加class就好办了，不知道有没有相关方法。
